const products = [
  {id:1,name:'Léonie',category:'Escarpins',price:129,desc:'Cuir ivoire · Talon 7 cm',image:'https://images.unsplash.com/photo-1560343090-f0409e92791a?auto=format&fit=crop&w=700&q=80',badge:'Nouveau'},
  {id:2,name:'Alba',category:'Baskets',price:110,desc:'Cuir blanc · Semelle souple',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=700&q=80',badge:'Best-seller'},
  {id:3,name:'Mila',category:'Bottines',price:155,desc:'Cuir chocolat · Talon 5 cm',image:'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=700&q=80',badge:''},
  {id:4,name:'Cassie',category:'Sandales',price:89,desc:'Cuir caramel · Bride fine',image:'https://images.unsplash.com/photo-1562273138-f46be4ebdf33?auto=format&fit=crop&w=700&q=80',badge:'Nouveau'},
  {id:5,name:'Iris',category:'Escarpins',price:139,desc:'Suède noir · Talon 8 cm',image:'https://images.unsplash.com/photo-1596703263926-eb0762ee17e4?auto=format&fit=crop&w=700&q=80',badge:''},
  {id:6,name:'Nina',category:'Baskets',price:99,desc:'Toile beige · Ligne rétro',image:'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=700&q=80',badge:''},
  {id:7,name:'Lou',category:'Bottines',price:149,desc:'Cuir noir · Fermeture zippée',image:'https://images.unsplash.com/photo-1542840410-3092f99611a3?auto=format&fit=crop&w=700&q=80',badge:''},
  {id:8,name:'June',category:'Sandales',price:79,desc:'Cuir doré · Bride croisée',image:'https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=700&q=80',badge:'-20%'}
];
let activeFilter='Tous', cart=[];
const grid=document.querySelector('#product-grid'), empty=document.querySelector('#empty-state');
function renderProducts(){let search=(document.querySelector('#search-input')?.value||'').toLowerCase();let list=products.filter(p=>(activeFilter==='Tous'||p.category===activeFilter)&&(!search||`${p.name} ${p.category} ${p.desc}`.toLowerCase().includes(search)));const sort=document.querySelector('#sort-products').value;if(sort==='price-low')list.sort((a,b)=>a.price-b.price);if(sort==='price-high')list.sort((a,b)=>b.price-a.price);grid.innerHTML=list.map(p=>`<article class="product-card"><div class="product-image"><img src="${p.image}" alt="Chaussures ${p.name}">${p.badge?`<span class="badge">${p.badge}</span>`:''}<button class="quick-add" data-add="${p.id}">Ajouter au panier +</button></div><div class="product-info"><div><strong>${p.name}</strong><small>${p.desc}</small></div><span class="product-price">${p.price.toFixed(2).replace('.',',')} €</span></div></article>`).join('');empty.style.display=list.length?'none':'block';grid.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',()=>addToCart(+b.dataset.add)));}
function addToCart(id){let p=products.find(x=>x.id===id), existing=cart.find(x=>x.id===id);if(existing)existing.qty++;else cart.push({...p,qty:1});renderCart();openCart();}
function renderCart(){document.querySelector('.cart-count').textContent=cart.reduce((sum,p)=>sum+p.qty,0);let box=document.querySelector('#cart-items');box.innerHTML=cart.length?cart.map(p=>`<div class="cart-line"><img src="${p.image}" alt="${p.name}"><div class="cart-line-info"><strong>${p.name}</strong><small>${p.category} · Quantité : ${p.qty}</small><b>${(p.price*p.qty).toFixed(2).replace('.',',')} €</b></div><button class="remove-item" data-remove="${p.id}" aria-label="Retirer ${p.name}">×</button></div>`).join(''):'<p class="cart-empty">Votre panier est encore vide.<br>Il est temps de trouver votre prochaine paire.</p>';document.querySelector('#cart-total').textContent=cart.reduce((s,p)=>s+p.price*p.qty,0).toFixed(2).replace('.',',')+' €';document.querySelector('.checkout').disabled=!cart.length;box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(p=>p.id!==+b.dataset.remove);renderCart()});}
function openCart(){document.querySelector('#cart-drawer').classList.add('open');document.querySelector('#overlay').classList.add('open')}function closeCart(){document.querySelector('#cart-drawer').classList.remove('open');document.querySelector('#overlay').classList.remove('open')}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProducts()});document.querySelector('#sort-products').onchange=renderProducts;document.querySelector('#cart-toggle').onclick=openCart;document.querySelector('#close-cart').onclick=closeCart;document.querySelector('#overlay').onclick=closeCart;document.querySelector('#search-toggle').onclick=()=>{document.querySelector('#search-bar').classList.toggle('open');document.querySelector('#search-input').focus()};document.querySelector('#close-search').onclick=()=>document.querySelector('#search-bar').classList.remove('open');document.querySelector('#search-input').oninput=renderProducts;document.querySelector('#all-products').onclick=()=>{activeFilter='Tous';document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='Tous'));renderProducts()};document.querySelectorAll('[data-category]').forEach(a=>a.onclick=()=>{activeFilter=a.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===activeFilter));renderProducts()});document.querySelector('#newsletter-form').onsubmit=e=>{e.preventDefault();document.querySelector('#newsletter-message').textContent='Merci ! Vous êtes bien inscrite à notre journal.';e.target.reset()};document.querySelector('.checkout').onclick=()=>alert('Merci pour votre commande ! Le paiement sera bientôt disponible.');
renderProducts();renderCart();
